#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#include <string>

const int LONGEST_PUZZLE_WORD = 15;
//const unsigned int upperLimit = 23;

const std::string introLines[] =
{
	"ROBCO INDUSTRIES (TM) TERMALINK PROTOCOL",
	"!!!! WARNING: LOCKOUT IMMINENT !!!!",
};
const int INTRO_LINE_COUNT = sizeof(introLines) / sizeof(std::string);

const int COLUMN_CHARACTER_WIDTH = 12;
const int HEX_CODE_LENGTH = 6;

const int COLUMN_COUNT = 2;
const int ANSWER_AREA_WIDTH = LONGEST_PUZZLE_WORD + 1;
const int TOTAL_COLUMN_WIDTH = HEX_CODE_LENGTH + 1 + COLUMN_CHARACTER_WIDTH + 1;
const int TOTAL_SCREEN_WIDTH = TOTAL_COLUMN_WIDTH * COLUMN_COUNT + ANSWER_AREA_WIDTH;

const int COLUMN_HEIGHT = 17;
const int LINES_BEFORE_COLUMNS = INTRO_LINE_COUNT + 3;
const int TOTAL_SCREEN_HEIGHT = COLUMN_HEIGHT + LINES_BEFORE_COLUMNS;

const int TOTAL_COLUMN_LINE_COUNT = COLUMN_HEIGHT * COLUMN_COUNT;

const COORD TOTAL_SIZE_COORD = { TOTAL_SCREEN_WIDTH, TOTAL_SCREEN_HEIGHT };
const COORD ORIGIN_COORD = { 0, 0 };


const WORD NORMAL_CHAR_ATTRIBUTES = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD HIGHLIGHTED_CHAR_ATTRIBUTES = BACKGROUND_GREEN | BACKGROUND_INTENSITY;

const int STARTING_ATTEMPT_COUNT = 5;

const char* FILLER_CHARACTERS = "$-/?|=+&^%!@#&*{}[]()<>,.'\"";
const int FILLER_CHARACTER_COUNT = strlen( FILLER_CHARACTERS );

const int TOTAL_COLUMNS_CHARACTER_COUNT = COLUMN_COUNT * COLUMN_CHARACTER_WIDTH * COLUMN_HEIGHT;

const int WORD_COUNT = 10;

#endif